/* Opt-in gate on the enrolled tab. Never changes site/account preferences. */
(()=>{
 globalThis.__ytdChallengeCleanup?.();const abort=new AbortController(),signal=abort.signal,id=crypto.randomUUID();let gate=null,busy=false,box=null,signature='',timer,rewatchToken,replayToken;
 const vid=()=>YTD_PLATFORM.videoIdFromUrl(location.href),video=()=>document.querySelector('.bpx-player-video-wrap video')||document.querySelector('video');
 function close(){box?.remove();box=null;signature='';}
 function show(){if(!gate?.blocked){close();return;}video()?.pause();const key=JSON.stringify([gate.id,vid(),gate.status]);if(key===signature&&box)return;close();signature=key;
  box=document.createElement('div');box.id='jude-challenge-gate';const shadow=box.attachShadow({mode:'open'});
  const style=document.createElement('style');style.textContent=':host{position:fixed;inset:auto 16px 20px;z-index:2147483647;display:block}section{box-sizing:border-box;max-width:620px;margin:auto;padding:20px;border-radius:14px;background:#f7f4ed;color:#302c26;border:1px solid #c7b8a7;box-shadow:0 8px 30px #0005;font:15px/1.6 system-ui}button,a{display:inline-block;cursor:pointer;padding:8px 12px;margin:5px;border:1px solid #bdcfc1;border-radius:8px;background:white;color:#254737;font:inherit;text-decoration:none}button:focus-visible,a:focus-visible{outline:3px solid #ce674c}h2{font-size:20px;margin:0}';shadow.append(style);
  const card=document.createElement('section');card.setAttribute('role','dialog');card.setAttribute('aria-label','本集闯关待完成');const h=document.createElement('h2');h.textContent='完成本集测试，再继续下一集';const p=document.createElement('p');p.textContent=gate.parentMode?'家长模式已暂停播放。请完成本集任务，测试达到 8 分后继续；解除模式需家长密钥。':'闯关尚未完成，已暂停播放。可回到本集测试，也可以退出闯关恢复自由观看。';card.append(h,p);
  const back=document.createElement('a');back.textContent='回到本集';back.href=YTD_PLATFORM.sourceUrl(gate.videoId,gate.position);card.append(back);
  const open=document.createElement('button');open.textContent='打开学习页测试';open.onclick=async()=>{try{const r=await chrome.runtime.sendMessage({action:'challengeOpen'});if(!r?.success)throw Error();p.textContent='请在句得侧栏点击“学习”，完成本集测试。';}catch{p.textContent='请点击句得扩展图标，进入“学习”完成测试。';}};card.append(open);
  const exit=document.createElement('button');exit.textContent=gate.parentMode?'请家长解除':'退出闯关';exit.onclick=async()=>{if(gate.parentMode){open.click();return;}if(!confirm('退出后保留记录，本次未通关。确认恢复自由观看？'))return;const r=await chrome.runtime.sendMessage({action:'challengeExit',sessionId:gate.id});if(r?.success){gate=null;close();}};card.append(exit);shadow.append(card);(document.fullscreenElement||document.documentElement).append(box);
 }
 async function pulse(){if(busy)return;busy=true;try{const v=video();const r=await chrome.runtime.sendMessage({action:'challengePulse',documentId:id,position:v?.currentTime||0,duration:Number.isFinite(v?.duration)?v.duration:0,videoTitle:document.title,playing:!!v&&!v.paused&&!v.ended,buffering:!v||v.readyState<3,seeking:!!v?.seeking,ended:!!v?.ended,visible:!document.hidden,online:navigator.onLine});if(r?.success){gate=r.gate;if(gate?.replay&&replayToken!==gate.replay.token){replayToken=gate.replay.token;const player=video();if(player){player.currentTime=gate.replay.start;gate.blocked=false;void player.play().catch(()=>{});}}if(gate?.replay&&video()?.currentTime>=gate.replay.end)gate.blocked=true;if(gate?.rewatchToken&&rewatchToken!==gate.rewatchToken){rewatchToken=gate.rewatchToken;const player=video();if(player){player.currentTime=0;player.pause();}}show();}}catch{if(gate?.parentMode){gate.blocked=true;show();}else cleanup();}finally{busy=false;}}
 function playback(e){if(!(e.target instanceof HTMLVideoElement))return;if(gate?.replay&&e.target.currentTime>=gate.replay.end){gate.blocked=true;e.target.pause();show();}if(gate&&(gate.blocked||gate.videoId!==vid())&&['play','playing'].includes(e.type))e.target.pause();void pulse();}
 for(const type of ['play','playing','pause','ended','seeking','seeked','waiting','timeupdate'])document.addEventListener(type,playback,{capture:true,signal});
 document.addEventListener('fullscreenchange',()=>{signature='';show();},{signal});window.addEventListener('pagehide',cleanup,{once:true,signal});
 function cleanup(){abort.abort();clearInterval(timer);close();}globalThis.__ytdChallengeCleanup=cleanup;timer=setInterval(pulse,1000);void pulse();
})();
